openapi: 3.0.0
info:
  description: Backend server docs for Enterios-Serverless
  version: "1.0.0"
  title: Enterios-Serverless
servers:
  - description: Dev Server
    url: http://localhost:7071/api/
  - description: Prod Server
    url: "https://bloggingwebsite-backend.herokuapp.com/api/v1/"

paths:
  /:
    get:
      tags:
        - Fetches home page info
      summary: Fetches home page info
      security:
        - Bearer: []
      responses:
        "200":
          description: Home page info fetched successfully
        "400":
          description: Invalid input
        "500":
          description: Internal Server Error

  /signup:
    post:
      tags:
        - User sign up
      summary: User sign up
      requestBody:
        $ref: "#/components/requestBodies/createUserInput"
      responses:
        "200":
          description: User signed up successfully
        "400":
          description: Invalid input
        "500":
          description: Internal Server Error

components:
  schemas:
    createUserInput:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string

  securitySchemes:
    Bearer:
      type: http
      scheme: Bearer
      bearerFormat: JWT

  requestBodies:
    createUserInput:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/createUserInput"
        application/xml:
          schema:
            $ref: "#/components/schemas/createUserInput"
      description: User sign up properties
      required: true
